### ISSUE TITLE
Build error with GCC v10.2.1

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#664]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | RHEL
OS Version             | 7
Architecture           | x86_64
UnifyFS Version        | develop

### Describe the problem you're observing
On LC `x86_64` systems, attempting to build UnifyFS with GCC v10.2.1 fails with several `multiple definitions of 'failed_clients'` errors.

### Describe how to reproduce the problem
Build UnifyFS with GCC v10.2.1 on a x86_64 system.

### Include any warning or errors or releveant debugging data
```
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-margo_server.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_client_rpc.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_group_rpc.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_inode.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_inode_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_p2p_rpc.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_request_manager.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_server.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_service_manager.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_server_pid.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_transfer.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_fops_rpc.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: multiple definition of `failed_clients'; unifyfsd-extent_tree.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/unifyfs_global.h:191: first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [unifyfsd] Error 1
```

**Comment by MichaelBrim** [comment]
this is fixed in PR #661

**Comment by MichaelBrim** [comment]
Only discovered it after the original heartbeat rpc PR went in.

**Comment by MichaelBrim** [comment]
@CamStan Since #661 was just merged, can you verify latest dev builds for you?

**Comment by CamStan** [comment]
@MichaelBrim, tried again. This error went away, but still failing to build with:

```
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_logio.o: in function `unifyfs_logio_alloc':
/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:569: undefined reference to `LOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:583: undefined reference to `UNLOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:607: undefined reference to `UNLOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:614: undefined reference to `LOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:629: undefined reference to `UNLOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:656: undefined reference to `UNLOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:670: undefined reference to `UNLOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:682: undefined reference to `UNLOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:684: undefined reference to `UNLOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_logio.o:/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:690: more undefined references to `UNLOCK_LOG_HEADER' follow
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: unifyfsd-unifyfs_logio.o: in function `unifyfs_logio_free':
/g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:746: undefined reference to `LOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:757: undefined reference to `UNLOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:762: undefined reference to `LOCK_LOG_HEADER'
/usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/10/ld: /g/g14/stanavig/UnifyFS/build-catalyst-gcc-10.2.1/server/src/../../../server/src/../../common/src/unifyfs_logio.c:773: undefined reference to `UNLOCK_LOG_HEADER'
collect2: error: ld returned 1 exit status
```

**Comment by MichaelBrim** [comment]
did you do a from scratch autogen/configure/build?

**Comment by CamStan** [comment]
Did it again from scratch just in case I didn't. Still failing.

**Comment by MichaelBrim** [comment]
What happens if you remove the 'inline' from the definitions of [UN]LOCK_LOG_HEADER in unifyfs_logio.c?

**Comment by CamStan** [comment]
> What happens if you remove the 'inline' from the definitions of [UN]LOCK_LOG_HEADER in unifyfs_logio.c?

Built and installed successfully with this change.

**Comment by MichaelBrim** [comment]
Ok, it seems it needs to be 'static inline' then. I've submitted PR #666 to fix 😈

**Comment by CamStan** [comment]
Tested again. Resolved by #666
